### ISSUE TITLE
Is there an S2Search API available ? 

### ISSUE THREAD

**Issue by TheoLvs** [allenai/s2search#1]
Hello ! 

Loves your work on SemanticScholar both from an academic and a ML perspective. 

I am struggling to see if there is an API to search your database from a query. I found the https://api.semanticscholar.org/ which only allows me to retrieve papers if you know the authors or the DOI-like identifiers. 
Is there something to query the database from a text query ? I have seen that https://www.connectedpapers.com/ was using SemanticScholar to power up their search engine. 

Thanks a lot, 
Theo

**Comment by sergeyf** [comment]
Thanks for the nice words.

Search is not part of our public API. We’ve whitelisted a few of the Connected Papers IPs so that they can hit our private API for search and autocomplete. Sorry about that!
