### ISSUE TITLE
Training data to reproduce & extend model training

### ISSUE THREAD

**Issue by ometaxas** [allenai/s2search#2]
Hi all!! External re-ranking on top of ES seems a promising alternative. Could you please also release the data which you use to train the LightGBM model to help us reproduce or extend model training?
Additionally to that, I'd like to ask you whether KenLM is also used in production settings (as my understanding from various S2 posts is that Specter is currently the LM of choice for most of semantic search and/or content-based recommendation tasks). 
Thank you

**Comment by sergeyf** [comment]
Howdy. Unfortunately the training data and training code are not available for this particular model. Sorry!

Yes, we use KenLM here. You'll see it when you download all the artifacts and you can see the KenLM models being loaded in the code here: https://github.com/allenai/s2search/blob/master/s2search/rank.py#L20

SPECTER isn't really a LM. It encodes sentences/paragraphs into vectors and is not used for search.

Cheers.

**Comment by ometaxas** [comment]
Indeed, Specter is a sentence encoder (based on a neural LM like SciBERT). I don't understand though why you mention that is not used for search as it can be leveraged in both Semantic Search & content-based recommendation scenarios.

**Comment by sergeyf** [comment]
We optimized for speed and interpretability. The goal was to make an old-school keyword based search, so when a user searches for specific words, they appear in the result somewhere.
